# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-16 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaCodeLookup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_code', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('latitude', models.CharField(max_length=200)),
                ('longitude', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Backpage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='backpage_timestamp')),
                ('frequency', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BackpageAdInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_title', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('latitude', models.CharField(max_length=200)),
                ('longitude', models.CharField(max_length=200)),
                ('ad_body', models.CharField(max_length=200)),
                ('photos', models.CharField(max_length=200)),
                ('post_id', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(verbose_name='backpage_ad_info_timestamp')),
                ('url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ImageToText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=200)),
                ('labels', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(verbose_name='image_to_text_timestamp')),
                ('phone_number', models.CharField(max_length=20)),
                ('latitude', models.CharField(max_length=200)),
                ('longitude', models.CharField(max_length=200)),
                ('image_url', models.CharField(max_length=200)),
                ('throw_away', models.CharField(max_length=200)),
            ],
        ),
    ]
